---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: pre-start
  image: 001575623345.dkr.ecr.eu-west-1.amazonaws.com/drone-tools:1.17.12
  commands:
  - pre-start-scripts
  environment:
    COUNTRY: it

- name: cache-restore
  image: 001575623345.dkr.ecr.eu-west-1.amazonaws.com/drone-tools:1.17.12
  commands:
  - . /etc/profile.d/ecs-credentials-endpoint
  - cache-restore
  environment:
    COUNTRY: it
  volumes:
  - name: ecs
    path: /etc/profile.d/ecs-credentials-endpoint
  - name: docker
    path: /var/run/docker.sock

- name: check-secrets
  image: 001575623345.dkr.ecr.eu-west-1.amazonaws.com/drone-tools:1.17.12
  commands:
  - . /etc/profile.d/ecs-credentials-endpoint
  - check-secrets-grants
  volumes:
  - name: ecs
    path: /etc/profile.d/ecs-credentials-endpoint

- name: build-image
  image: 001575623345.dkr.ecr.eu-west-1.amazonaws.com/drone-tools:1.17.12
  commands:
  - sed -i 's/USER node/USER root/g' ./Dockerfile
  - docker build -t prima/pyxis-npm-ci:1 ./
  volumes:
  - name: docker
    path: /var/run/docker.sock
  - name: docker-conf
    path: /root/.docker
  depends_on:
  - cache-restore

- name: dependencies
  image: prima/pyxis-npm-ci:1
  commands:
  - yarn
  environment:
    YARN_CACHE_FOLDER: /drone/src/.cache/yarn
  depends_on:
  - pre-start
  - build-image

- name: build
  image: prima/pyxis-npm-ci:1
  commands:
  - yarn run build:prod
  environment:
    YARN_CACHE_FOLDER: /drone/src/.cache/yarn
  depends_on:
  - dependencies

- name: cache-save
  image: 001575623345.dkr.ecr.eu-west-1.amazonaws.com/drone-tools:1.17.12
  commands:
  - . /etc/profile.d/ecs-credentials-endpoint
  - cache-save .cache node_modules
  environment:
    COUNTRY: it
  volumes:
  - name: ecs
    path: /etc/profile.d/ecs-credentials-endpoint
  - name: docker
    path: /var/run/docker.sock
  when:
    branch:
    - master
  depends_on:
  - dependencies
  - build

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
- name: ecs
  host:
    path: /etc/profile.d/ecs-credentials-endpoint
- name: docker-conf
  host:
    path: /home/ec2-user/.docker

trigger:
  event:
  - push

---
kind: pipeline
name: email-failure

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: email-failure
  image: drillster/drone-email
  settings:
    from: noreply@prima.it
    host: email-smtp.eu-west-1.amazonaws.com
  environment:
    PLUGIN_PASSWORD:
      from_secret: email_password
    PLUGIN_USERNAME:
      from_secret: email_username

trigger:
  event:
  - push
  status:
  - failure

depends_on:
- default

---
kind: signature
hmac: 9ebc5e53fe1743a13e0f58104804671fbddb7b921df175f6a83c16a4883b6102

...
