apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "pyxis-npm"
  description: "Pyxis-NPM is the standard way to integrate the Pyxis Design"
spec:
  type: "library"
  lifecycle: production
  owner: "group:default/team-pyxis"
  system: prima.it
