apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "pyxis-npm"
  description: "This package is legacy and is currently maintained in maintenance mode. Use Pyxis instead."
spec:
  type: "library"
  lifecycle: production
  owner: "group:default/team-pyxis"
  system: prima.it
